[CORE-9192] Node 16 migration
goodhood-eu/nebenan-components pull request #65
Opened 2022-01-31 09:04 UTC by iamuchejude

[JIRA Link](https://jira.nebenan.de/browse/CORE-9192)

2022-01-31 09:18 UTC, iamuchejude commented
UPDATE: `gulp compile` is failing after updating.

```sh
fs.js:47
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:47:5
    at req_ (/Users/jude/Projects/nebenan-components/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/jude/Projects/nebenan-components/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/jude/Projects/nebenan-components/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
```

2022-02-04 08:01 UTC, peterhass requested changes
Since you did the stylelint-config and eslint-config major updates, you have to fix all the linting errors (most should be autofixable)

2022-02-04 08:01 UTC, peterhass commented on package.json
> +  "version": "12.1.0",
I would opt for `12.0.1` since you're not adding any new functionality but only updating deps

2022-02-04 08:18 UTC, eliasbraun approved these changes

2022-02-04 16:57 UTC, peterhass approved these changes

2022-02-04 18:06 UTC, merged